{
 "title": "Squid Graylog",
 "tags": [
  "Proxies",
  "Logs Analyzer",
  "Elasticsearch"
 ],
 "time": { "from": "now/d", "to": "now/d" },
 "templating": {
  "list": [
   {
    "name": "user",
    "label": "User",
    "query": "{\"find\": \"terms\", \"field\":\"User\",\"size\": \"1000000\" }"
   },
   {
    "name": "URIHost",
    "label": "Destination",
    "query": "{\"find\": \"terms\", \"field\":\"URI_Host\",  \"query\": \"User:$user AND NOT Result_Code:TCP_DENIED\", \"size\": \"1000000\" }"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Trafic",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 0 },
   "format": "decbytes",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "real_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "Bytes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "User:$user AND URI_Host:$URIHost  AND (Method:CONNECT OR Method:GET OR Method:POST) AND NOT Result_Code:\"TCP_DENIED\"",
     "timeField": "real_timestamp"
    }
   ]
  },
  {
   "title": "Top User",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 10, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "User",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "1" },
       "type": "terms"
      },
      { "field": "real_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "User:$user AND NOT Result_Code:\"TCP_DENIED\" AND URI_Host:$URIHost",
     "timeField": "real_timestamp"
    }
   ]
  },
  {
   "title": "Credits",
   "type": "text",
   "gridPos": { "h": 11, "w": 4, "x": 20, "y": 0 },
   "content": "![https://www.sysadminsdecuba.com](https://www.sysadminsdecuba.com/wp-content/uploads/2017/10/cropped-placeholder-medium.png)\n# Squid Dashboard Logs Analisys.\nDocumentation in [sysadminsdecuba](https://www.sysadminsdecuba.com)\n\nDesing by: Omar Padrón Capote\n\nemail: omar@mpcfg.co.cu"
  },
  {
   "title": "Top Site",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "URI_Host",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "1" },
       "type": "terms"
      },
      { "field": "real_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "User:$user AND NOT Result_Code:\"TCP_DENIED\" AND NOT URI_HOST:\"ocsp.int-x3.letsencrypt.org\" AND URI_Host:$URIHost",
     "timeField": "real_timestamp"
    }
   ]
  },
  { "title": "General Analisys", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "real_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "User:$user AND URI_Host:$URIHost AND (Method:CONNECT OR Method:GET OR Method:POST) AND NOT Result_Code:\"TCP_DENIED\"",
     "timeField": "real_timestamp"
    }
   ]
  },
  {
   "title": "Geo Destination",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 21 },
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "URI_Host",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      { "field": "geo_location", "id": "2", "settings": { "precision": 7 }, "type": "geohash_grid" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "User:$user AND URI_Host:$URIHost  AND (Method:CONNECT OR Method:GET OR Method:POST) AND NOT Result_Code:\"TCP_DENIED\"",
     "timeField": "real_timestamp"
    }
   ]
  },
  {
   "title": "Squid Codes",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 21 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "Result_Code",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "real_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "User:$user AND URI_Host:$URIHost",
     "timeField": "real_timestamp"
    }
   ]
  },
  {
   "title": "Proxy Authentication Required",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 21 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "alias": "Code {{term Status_Code}} {{term User}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "Status_Code",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "User",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      { "field": "real_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "User:$user  AND Status_Code:\"407\" AND URI_Host:$URIHost",
     "timeField": "real_timestamp"
    }
   ]
  },
  {
   "title": "Forbidden Access",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "alias": "Code {{term Status_Code}} {{term User}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "Status_Code",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "User",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      { "field": "real_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "User:$user AND URI_Host:$URIHost  AND Status_Code:\"403\"",
     "timeField": "real_timestamp"
    }
   ]
  },
  {
   "title": "Hits of users",
   "type": "table",
   "gridPos": { "h": 11, "w": 4, "x": 0, "y": 35 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "User",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "User:$user AND NOT Result_Code:\"TCP_DENIED\" AND URI_Host:$URIHost",
     "timeField": "real_timestamp"
    }
   ]
  },
  {
   "title": "Traffic by User",
   "type": "table",
   "gridPos": { "h": 11, "w": 3, "x": 4, "y": 35 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "User",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "Bytes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "User:$user AND NOT Result_Code:\"TCP_DENIED\" AND URI_Host:$URIHost  AND (Method:CONNECT OR Method:GET OR Method:POST)",
     "timeField": "real_timestamp"
    }
   ]
  },
  {
   "title": "Destinations",
   "type": "table",
   "gridPos": { "h": 11, "w": 5, "x": 7, "y": 35 },
   "targets": [
    {
     "alias": "url",
     "bucketAggs": [
      {
       "fake": true,
       "field": "URI_Host",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "User:$user  AND NOT Result_Code:\"TCP_DENIED\"  AND NOT URI_HOST:\"ocsp.int-x3.letsencrypt.org\" AND URI_Host:$URIHost",
     "timeField": "real_timestamp"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "bytes", "label": "Megabyte Traffic" }
   ],
   "targets": [
    {
     "alias": "Trafic",
     "bucketAggs": [
      { "field": "real_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "Bytes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "User:$user AND URI_Host:$URIHost",
     "timeField": "real_timestamp"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Top Sites",
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "URI_Host",
       "id": "12",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" },
      {
       "field": "Bytes",
       "id": "9",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "Duration",
       "id": "11",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "User:$user AND URI_Host:$URIHost  AND (Method:CONNECT OR Method:GET OR Method:POST) AND NOT Result_Code:\"TCP_DENIED\"",
     "timeField": "real_timestamp"
    }
   ]
  }
 ]
}